version: '3.6'
services:
  nginx:
    build: nginx 
    links:
      - php
    ports: 
      - 443:443
      - 80:80
    volumes:
    - ./yaspcc:/yaspcc
  php:
    build: php
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=yasp.cc
    links: 
      - redis
    volumes:
      - ./yaspcc:/yaspcc
  php-cron:
    build: php-cron
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=yasp.cc
    links:
    - redis
    volumes:
    - ./yaspcc:/yaspcc
  redis:
    image: redis
