FROM php:7.2-fpm

RUN docker-php-ext-install -j $(nproc) mysqli
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
     && php composer-setup.php \
     && php -r "unlink('composer-setup.php');" \
     && chmod +x composer.phar \
     && mv composer.phar /usr/local/bin/composer
RUN mkdir /scripts
COPY ./startup.sh /scripts/startup.sh
WORKDIR /scripts
RUN chmod +x startup.sh
ENTRYPOINT ["/scripts/startup.sh"]